version: '3.4'

services:
  mysql:
    build: mysql/
    container_name: docker-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/etc/my.cnf:/etc/mysql/my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 1  
